set(0,'defaultAxesFontSize',8,...
    'defaultAxesTitleFontSize', 12,...
    'DefaultAxesTitleFontWeight', 'normal', ...
    'DefaultAxesTitleFontSizeMultiplier', 1.25) ;
disp('root property values set');